import {
    BooleanColumn,
    ChoiceColumn,
    DateColumn,
    DateTimeColumn,
    ListColumn,
    MultiLineTextColumn,
    ReferenceColumn,
    StringColumn,
    Table,
} from '@servicenow/sdk/core'
import { x_2166123_hr_acc_0_rob_access } from './rob-access-item-reference.now'
import { x_2166123_hr_acc_0_rob_auth } from './rob-authorization-form.now'

const supervisorExceptionChoices = {
    missing_supervisor: 'Missing supervisor',
    invalid_supervisor: 'Invalid supervisor',
    inactive_supervisor: 'Inactive supervisor',
    self_supervisor: 'Supervisor matches requester',
    missing_position: 'Missing position',
    missing_organization: 'Missing organization / DIR-DIV',
    missing_required_access_end_date: 'Missing required access end date',
    missing_operations_manager: 'Missing Operations Manager',
    invalid_operations_manager: 'Invalid Operations Manager',
    inactive_operations_manager: 'Inactive Operations Manager',
    EX_INVALID_CONFIG: 'Invalid ROB configuration',
    EX_MISSING_REQUIRED_DATA: 'Missing required decision data',
    EX_MISSING_SUPERVISOR: 'Missing supervisor decision input',
    EX_MISSING_END_DATE: 'Missing required access end date',
    EX_MISSING_OM: 'Missing Operations Manager',
    EX_INVALID_ACCESS_ITEM: 'Invalid or inactive requested access item',
    EX_DUPLICATE_OPEN_CASE: 'Duplicate equivalent open request',
    EX_CONFLICTING_ACTIVE_FORMS: 'Conflicting active authorizations',
    EX_INCOMPLETE_AUTHORIZATION_HISTORY: 'Incomplete authorization history',
    EX_AMBIGUOUS_MATERIAL_CHANGE: 'Ambiguous material context change',
    EX_UNRESOLVED_ANNUAL_RENEWAL_RULE: 'Unresolved annual renewal trigger',
}

const employmentTypeChoices = {
    federal_employee: 'Federal Employee',
    contractor: 'Contractor',
    ipa: 'IPA',
    auditor_investigator: 'Auditor / Investigator',
}

const decisionReasonChoices = {
    NEW_NO_PRIOR_FORM: 'New — no prior form',
    NEW_PRIOR_REVOKED: 'New — prior form revoked',
    NEW_NO_CURRENT_FORM: 'New — no current governing form',
    REUSE_FULLY_COVERED: 'Reuse — fully covered',
    AMD_PARTIAL_COVERAGE: 'Amendment — partial coverage',
    AMD_NO_COVERAGE_ACTIVE_FORM: 'Amendment — new scope on active form',
    AMD_ORG_CHANGE: 'Amendment — organization change',
    AMD_POSITION_ROLE_CHANGE: 'Amendment — position or role change',
    AMD_JUSTIFICATION_CHANGE: 'Amendment — justification change',
    AMD_MULTIPLE_MATERIAL_CHANGES: 'Amendment — multiple material changes',
    REN_EXPIRED: 'Renewal — expired',
    REN_LAPSED: 'Renewal — lapsed',
    REN_OBSOLETE_VERSION: 'Renewal — obsolete form version',
    REN_ANNUAL_RECERTIFICATION: 'Renewal — annual recertification',
}

const caseSecuritySchema = {
    x_2166123_hr_acc_0_authorization_path: ChoiceColumn({
        label: 'ROB Authorization Path',
        choices: {
            new: 'New', reuse: 'Reuse', amendment: 'Amendment',
            renewal: 'Renewal', exception: 'Exception Review',
        },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_decision_reason: StringColumn({
        label: 'ROB Decision Reason',
        maxLength: 80,
        choices: decisionReasonChoices,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_decision_evaluated_at: DateTimeColumn({
        label: 'ROB Decision Evaluated At',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_existing_authorization_status: ChoiceColumn({
        label: 'ROB Existing Authorization Status',
        choices: {
            none: 'None', active: 'Active', expired: 'Expired',
            lapsed: 'Lapsed', superseded: 'Superseded', revoked: 'Revoked',
            obsolete_version: 'Obsolete Version', denied: 'Denied',
        },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_evaluated_authorization: ReferenceColumn({
        label: 'ROB Evaluated Authorization',
        referenceTable: x_2166123_hr_acc_0_rob_auth.name,
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_covered_access: ListColumn({
        label: 'ROB Covered Access',
        referenceTable: x_2166123_hr_acc_0_rob_access.name,
        maxLength: 1000,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_uncovered_access: ListColumn({
        label: 'ROB Uncovered Access',
        referenceTable: x_2166123_hr_acc_0_rob_access.name,
        maxLength: 1000,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_proposed_expiration_date: DateColumn({
        label: 'ROB Proposed Expiration Date',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_requires_supervisor_approval: BooleanColumn({
        label: 'ROB Requires Supervisor Approval',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_material_context_change: BooleanColumn({
        label: 'ROB Material Context Change',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_renewal_reason: StringColumn({
        label: 'ROB Renewal Reason',
        maxLength: 80,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_duplicate_case: ReferenceColumn({
        label: 'ROB Duplicate Case',
        referenceTable: 'sn_hr_core_case',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_employment_type: ChoiceColumn({
        label: 'Employment Type Snapshot',
        choices: employmentTypeChoices,
    }),
    x_2166123_hr_acc_0_access_end_date: DateColumn({
        label: 'Access End Date',
    }),
    x_2166123_hr_acc_0_requested_items: ListColumn({
        label: 'ROB Requested Access Items',
        referenceTable: x_2166123_hr_acc_0_rob_access.name,
        maxLength: 1000,
    }),
    x_2166123_hr_acc_0_position_title: StringColumn({
        label: 'Position Title Snapshot',
        maxLength: 160,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_organization_snapshot: ReferenceColumn({
        label: 'Organization / DIR-DIV Snapshot',
        referenceTable: 'cmn_department',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_supervisor_snapshot: ReferenceColumn({
        label: 'Supervisor Snapshot',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_exception_review_required: BooleanColumn({
        label: 'ROB Exception Review Required',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_exception_reason: StringColumn({
        label: 'ROB Exception Reason',
        maxLength: 80,
        choices: supervisorExceptionChoices,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_authorization_processing_blocked: BooleanColumn({
        label: 'ROB Authorization Processing Blocked',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_requires_employee_signature: BooleanColumn({
        label: 'ROB Requires Employee Signature',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_requires_supervisor_signature: BooleanColumn({
        label: 'ROB Requires Supervisor Signature',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_fulfillment_gate_complete: BooleanColumn({
        label: 'ROB Fulfillment Gate Complete',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_attestation_status: ChoiceColumn({
        label: 'ROB Reuse Attestation Status',
        choices: {
            pending: 'Pending', approved: 'Approved', denied: 'Denied',
            invalidated: 'Invalidated',
        },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_supervisor_decision: ChoiceColumn({
        label: 'ROB Reuse Supervisor Decision',
        choices: { approved: 'Approved', denied: 'Denied' },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_supervisor_signer: ReferenceColumn({
        label: 'ROB Reuse Supervisor Signer',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_supervisor_signature_at: DateTimeColumn({
        label: 'ROB Reuse Supervisor Signature At',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_document_task: ReferenceColumn({
        label: 'ROB Reuse Document Task',
        referenceTable: 'sn_doc_task',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_document_execution: ReferenceColumn({
        label: 'ROB Reuse Document Execution',
        referenceTable: 'sn_doc_task_execution',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_attestation_completed_at: DateTimeColumn({
        label: 'ROB Reuse Attestation Completed At',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_attestation_context: StringColumn({
        label: 'ROB Reuse Attestation Context',
        maxLength: 1000,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_correction_requested: BooleanColumn({
        label: 'ROB Snapshot Correction Requested',
        default: false,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_correction_reason: StringColumn({
        label: 'ROB Snapshot Correction Reason',
        maxLength: 1000,
        audit: true,
    }),
    x_2166123_hr_acc_0_prior_position_title: StringColumn({
        label: 'Prior Position Title Snapshot',
        maxLength: 160,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_prior_organization_snapshot: ReferenceColumn({
        label: 'Prior Organization / DIR-DIV Snapshot',
        referenceTable: 'cmn_department',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_prior_supervisor_snapshot: ReferenceColumn({
        label: 'Prior Supervisor Snapshot',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_corrected_by: ReferenceColumn({
        label: 'ROB Snapshot Corrected By',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_corrected_at: DateTimeColumn({
        label: 'ROB Snapshot Corrected At',
        readOnly: true,
        audit: true,
    }),
}

const workforceCaseSecuritySchema = {
    x_2166123_hr_acc_0_authorization_path: ChoiceColumn({
        label: 'ROB Authorization Path',
        choices: {
            new: 'New', reuse: 'Reuse', amendment: 'Amendment',
            renewal: 'Renewal', exception: 'Exception Review',
        },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_decision_reason: StringColumn({
        label: 'ROB Decision Reason',
        maxLength: 80,
        choices: decisionReasonChoices,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_decision_evaluated_at: DateTimeColumn({
        label: 'ROB Decision Evaluated At',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_existing_authorization_status: ChoiceColumn({
        label: 'ROB Existing Authorization Status',
        choices: {
            none: 'None', active: 'Active', expired: 'Expired',
            lapsed: 'Lapsed', superseded: 'Superseded', revoked: 'Revoked',
            obsolete_version: 'Obsolete Version', denied: 'Denied',
        },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_evaluated_authorization: ReferenceColumn({
        label: 'ROB Evaluated Authorization',
        referenceTable: x_2166123_hr_acc_0_rob_auth.name,
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_covered_access: ListColumn({
        label: 'ROB Covered Access',
        referenceTable: x_2166123_hr_acc_0_rob_access.name,
        maxLength: 1000,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_uncovered_access: ListColumn({
        label: 'ROB Uncovered Access',
        referenceTable: x_2166123_hr_acc_0_rob_access.name,
        maxLength: 1000,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_proposed_expiration_date: DateColumn({
        label: 'ROB Proposed Expiration Date',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_requires_supervisor_approval: BooleanColumn({
        label: 'ROB Requires Supervisor Approval',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_material_context_change: BooleanColumn({
        label: 'ROB Material Context Change',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_renewal_reason: StringColumn({
        label: 'ROB Renewal Reason',
        maxLength: 80,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_duplicate_case: ReferenceColumn({
        label: 'ROB Duplicate Case',
        referenceTable: 'sn_hr_core_case',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_employment_type: ChoiceColumn({
        label: 'Employment Type Snapshot',
        choices: employmentTypeChoices,
    }),
    x_2166123_hr_acc_0_access_end_date: DateColumn({
        label: 'Access End Date',
    }),
    x_2166123_hr_acc_0_requested_items: ListColumn({
        label: 'ROB Requested Access Items',
        referenceTable: x_2166123_hr_acc_0_rob_access.name,
        maxLength: 1000,
    }),
    x_2166123_hr_acc_0_operations_manager: ReferenceColumn({
        label: 'Operations Manager',
        referenceTable: 'sys_user',
        referenceQual: 'active=true',
        useReferenceQualifier: 'simple',
        cascadeRule: 'clear',
    }),
    x_2166123_hr_acc_0_position_title: StringColumn({
        label: 'Position Title Snapshot',
        maxLength: 160,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_organization_snapshot: ReferenceColumn({
        label: 'Organization / DIR-DIV Snapshot',
        referenceTable: 'cmn_department',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_supervisor_snapshot: ReferenceColumn({
        label: 'Supervisor Snapshot',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_exception_review_required: BooleanColumn({
        label: 'ROB Exception Review Required',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_exception_reason: StringColumn({
        label: 'ROB Exception Reason',
        maxLength: 80,
        choices: supervisorExceptionChoices,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_authorization_processing_blocked: BooleanColumn({
        label: 'ROB Authorization Processing Blocked',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_requires_employee_signature: BooleanColumn({
        label: 'ROB Requires Employee Signature',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_requires_supervisor_signature: BooleanColumn({
        label: 'ROB Requires Supervisor Signature',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_fulfillment_gate_complete: BooleanColumn({
        label: 'ROB Fulfillment Gate Complete',
        default: false,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_attestation_status: ChoiceColumn({
        label: 'ROB Reuse Attestation Status',
        choices: {
            pending: 'Pending', approved: 'Approved', denied: 'Denied',
            invalidated: 'Invalidated',
        },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_supervisor_decision: ChoiceColumn({
        label: 'ROB Reuse Supervisor Decision',
        choices: { approved: 'Approved', denied: 'Denied' },
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_supervisor_signer: ReferenceColumn({
        label: 'ROB Reuse Supervisor Signer',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_supervisor_signature_at: DateTimeColumn({
        label: 'ROB Reuse Supervisor Signature At',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_document_task: ReferenceColumn({
        label: 'ROB Reuse Document Task',
        referenceTable: 'sn_doc_task',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_document_execution: ReferenceColumn({
        label: 'ROB Reuse Document Execution',
        referenceTable: 'sn_doc_task_execution',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_attestation_completed_at: DateTimeColumn({
        label: 'ROB Reuse Attestation Completed At',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_reuse_attestation_context: StringColumn({
        label: 'ROB Reuse Attestation Context',
        maxLength: 1000,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_correction_requested: BooleanColumn({
        label: 'ROB Snapshot Correction Requested',
        default: false,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_correction_reason: StringColumn({
        label: 'ROB Snapshot Correction Reason',
        maxLength: 1000,
        audit: true,
    }),
    x_2166123_hr_acc_0_prior_position_title: StringColumn({
        label: 'Prior Position Title Snapshot',
        maxLength: 160,
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_prior_organization_snapshot: ReferenceColumn({
        label: 'Prior Organization / DIR-DIV Snapshot',
        referenceTable: 'cmn_department',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_prior_supervisor_snapshot: ReferenceColumn({
        label: 'Prior Supervisor Snapshot',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_corrected_by: ReferenceColumn({
        label: 'ROB Snapshot Corrected By',
        referenceTable: 'sys_user',
        cascadeRule: 'clear',
        readOnly: true,
        audit: true,
    }),
    x_2166123_hr_acc_0_snapshot_corrected_at: DateTimeColumn({
        label: 'ROB Snapshot Corrected At',
        readOnly: true,
        audit: true,
    }),
}

export const sn_hr_core_case_payroll = Table({
    augments: 'sn_hr_core_case_payroll',
    schema: caseSecuritySchema,
})

export const sn_hr_core_case_workforce_admin = Table({
    augments: 'sn_hr_core_case_workforce_admin',
    schema: workforceCaseSecuritySchema,
})

export const sn_hr_core_task = Table({
    augments: 'sn_hr_core_task',
    schema: {
        x_2166123_hr_acc_0_rob_task_type: StringColumn({
            label: 'ROB Task Type',
            maxLength: 40,
            choices: {
                staffing_fulfillment: 'Staffing Fulfillment',
                analytics_fulfillment: 'Analytics Fulfillment',
                operations_manager_arm_assignment: 'Operations Manager ARM Role Assignment',
                exception_review: 'Exception Review',
            },
            readOnly: true,
            audit: true,
        }),
        x_2166123_hr_acc_0_fulfillment_business_key: StringColumn({
            label: 'ROB Fulfillment Business Key',
            maxLength: 100,
            readOnly: true,
            audit: true,
            unique: true,
        }),
        x_2166123_hr_acc_0_related_authorization: ReferenceColumn({
            label: 'Related ROB Authorization Form',
            referenceTable: x_2166123_hr_acc_0_rob_auth.name,
            cascadeRule: 'clear',
            readOnly: true,
            audit: true,
        }),
        x_2166123_hr_acc_0_rob_access_items: ListColumn({
            label: 'ROB Access Items',
            referenceTable: x_2166123_hr_acc_0_rob_access.name,
            readOnly: true,
            audit: true,
        }),
        x_2166123_hr_acc_0_external_provisioning_system: StringColumn({
            label: 'External Provisioning System',
            maxLength: 40,
            readOnly: true,
            audit: true,
            choices: {
                arm: 'ARM',
                fpps_wtts: 'FPPS / WTTS',
                eopf: 'eOPF',
                usa_staffing: 'USA Staffing',
                other: 'Other',
                not_applicable: 'Not Applicable',
            },
        }),
        x_2166123_hr_acc_0_external_target_system: StringColumn({
            label: 'External Target System',
            maxLength: 80,
            readOnly: true,
            audit: true,
            choices: {
                oas: 'OAS / Workforce Profile Charts',
                fpps_wtts: 'FPPS / WTTS',
                eopf: 'eOPF',
                usa_staffing: 'USA Staffing',
                other: 'Other',
                not_applicable: 'Not Applicable',
            },
        }),
        x_2166123_hr_acc_0_fulfillment_outcome: StringColumn({
            label: 'ROB Fulfillment Outcome',
            maxLength: 40,
            audit: true,
            choices: {
                provisioning_completed: 'Provisioning Completed',
                waived: 'Formally Waived',
                not_required: 'Not Required',
                failed_exception: 'Failed / Exception',
            },
        }),
        x_2166123_hr_acc_0_completion_evidence: MultiLineTextColumn({
            label: 'ROB Completion Evidence',
            maxLength: 4000,
            audit: true,
        }),
        x_2166123_hr_acc_0_provisioning_completed: BooleanColumn({
            label: 'ROB Provisioning Completed',
            default: false,
            audit: true,
        }),
        x_2166123_hr_acc_0_completion_timestamp: DateTimeColumn({
            label: 'ROB Completion Date/Time',
            readOnly: true,
            audit: true,
        }),
        x_2166123_hr_acc_0_exception_reason: MultiLineTextColumn({
            label: 'ROB Exception Reason',
            maxLength: 4000,
            audit: true,
        }),
        x_2166123_hr_acc_0_formally_waived: BooleanColumn({
            label: 'ROB Formally Waived',
            default: false,
            readOnly: true,
            audit: true,
        }),
        x_2166123_hr_acc_0_waiver_reason: MultiLineTextColumn({
            label: 'ROB Waiver Reason',
            maxLength: 4000,
            audit: true,
        }),
        x_2166123_hr_acc_0_waived_by: ReferenceColumn({
            label: 'ROB Waived By',
            referenceTable: 'sys_user',
            cascadeRule: 'clear',
            readOnly: true,
            audit: true,
        }),
        x_2166123_hr_acc_0_waiver_date_time: DateTimeColumn({
            label: 'ROB Waiver Date/Time',
            readOnly: true,
            audit: true,
        }),
    },
})
