import '@servicenow/sdk/global'
import type { Table } from '@servicenow/sdk/core'
import type { sn_hr_core_case } from './sn_hr_core/data/table/sn_hr_core_case.d.now'
import type { sn_hr_core_task } from './sn_hr_core/data/table/sn_hr_core_task.d.now'
import type { sys_user } from './global/data/table/sys_user.d.now'
import type { sys_user_group } from './global/data/table/sys_user_group.d.now'

// Generated by ServiceNow SDK

declare global {
    namespace Now {
        namespace Internal {
            namespace TableSchemas {
                interface sn_hr_core_case extends Helper<typeof sn_hr_core_case> {}
                interface sn_hr_core_task extends Helper<typeof sn_hr_core_task> {}
                interface sys_user extends Helper<typeof sys_user> {}
                interface sys_user_group extends Helper<typeof sys_user_group> {}
            }

            interface Tables {
                sn_hr_core_case: Table<TableSchemas.sn_hr_core_case, 'task'>
                sn_hr_core_task: Table<TableSchemas.sn_hr_core_task, 'task'>
                sys_user: Table<TableSchemas.sys_user>
                sys_user_group: Table<TableSchemas.sys_user_group>
            }
        }
    }
}
